//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SessionProgrameSubjectSettingTable
    {
        public int SessionProgramSubjectSettingTableID { get; set; }
        public int SessionID { get; set; }
        public int ProgramID { get; set; }
        public int ClassID { get; set; }
        public int SubjectID { get; set; }
        public string Name { get; set; }
        public string RegDate { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
    
        public virtual AnnualTable AnnualTable { get; set; }
        public virtual ClassTable ClassTable { get; set; }
        public virtual ProgramTable ProgramTable { get; set; }
        public virtual SessionTable SessionTable { get; set; }
        public virtual SubjectTable SubjectTable { get; set; }
    }
}
